# A minimal, safe, text-only configuration for i3status-rust

[[block]]
block = "time"
interval = 5
format = "%a %d %b %H:%M"

[[block]]
block = "cpu"
interval = 1
format = "CPU: $util" # Removed the icon

[[block]]
block = "memory"
format = "MEM: $mem_used.eng(w:2,p:M)/$mem_total.eng(w:2,p:M)B" # Removed the icon

[[block]]
block = "sound"
format = "VOL: $volume" # Simplified format

[[block]]
block = "networkmanager"
format = "NET: {ssid}" # Simplified format